### ISSUE TITLE
Add `api` in metrics url

### ISSUE THREAD

**Issue by clkao** [yuvipanda/nbresuse#11]
We have seen noticeable jupyterhub performance degradation and finally tracked to the use of jupyterlab-statusbar in the new default notebook image.  When a user has the notebook server stopped, the metrics endpoint is hit continuously if the browser is left open.

As currently the metrics url are not with `api` in it, it is not guarded by [JupyterHub's short circuit for inactive users](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/handlers/base.py#L1101-L1105) but instead gets redirected to the hml spawner page for the xhr requests. If the spawner page happens to do anything fancy such as retrieving auth_state, it becomes quite an issue when there are lots of sessions like this.

The proposed fixed is to make the handler in nbresuse listen on `/api/metrics` instead of `/metrics`, add a redirect for compatibility, and patch jupyterlab-statusbar to use the new url.

(credit goes to @popcornylu for logs and performance analysis)

**Comment by yuvipanda** [comment]
@clkao sounds good to me! Eventually I want to just make this be part of notebook's prometheus metrics, but that's gonna take a bit of time and this feels like a good workaround.

Do you think you'll have time for a PR?

**Comment by krinsman** [comment]
This seems to be fixed as of version 0.3.3 and later (which integrates/utilizes the Prometheus metric PR that Yuvi made on `notebook`), so I am assuming that this has been resolved or at the very least is now out-of-date. Please let us know if a similar problem is still occurring, preferably by opening a new issue.
