### ISSUE TITLE
Additional unit for big memory usage

### ISSUE THREAD

**Issue by HeymoKou** [yuvipanda/nbresuse#20]
![image](https://user-images.githubusercontent.com/8154886/60875232-5fe10800-a274-11e9-9caf-e9d339e2e525.png)

Would it be possible to change size unit automatically with bigger data size?
Thank you.

**Comment by krinsman** [comment]
@HeymoKou  Are you still having this issue? 

It looks like it's been fixed (at least as of versions 0.3.3 and 0.3.4 on PyPI) https://github.com/yuvipanda/nbresuse/blob/master/nbresuse/static/main.js#L28

At the very least I see GB when I use it.

I am closing this provisionally in case it has already been resolved, but please let me know if it should be reopened.
