### ISSUE TITLE
Incompatible with Builtin Prometheus Metrics?

### ISSUE THREAD

**Issue by samuelmanzer** [yuvipanda/nbresuse#32]
Hi there, 

Love this extension - just wanted to check for clarification on how it is supposed to overlap with the builtin notebook prometheus metrics. I noticed when I install it, it takes over the metrics endpoint:

```
curl 'localhost:8888/metrics?token=...'
{"rss": 57704448, "limits": {}}
```

This seems to conflict with these metrics:

https://github.com/jupyter/notebook/blob/master/notebook/prometheus/metrics.py

Just wanted to check if this is expected or if I'm installing it wrong

**Comment by krinsman** [comment]
This is a good question!

To make sure we're on the same page, are we talking about NBResuse installed via PyPI? Or NBResuse installed from source on GitHub? Which version of NBResuse do you see when running `pip list`, for example?

The latter version is newer and intended to work better with Prometheus than the one on PyPI.

**Comment by krinsman** [comment]
@samuelmanzer Did the response above help? The latest versions should be compatible with Prometheus metrics -- try version 0.3.4 on PyPi.

For now I am provisionally closing this issue -- please let me know if I should reopen it.

**Comment by samuelmanzer** [comment]
I apologize for the delay in my response - I can confirm that `0.3.4` on PyPi does not clobber the prometheus metrics - thanks!

**Comment by colmaengus** [comment]
I'm using 0.3.6 from PyPi and the /metrics endpoint is being used therefore clobbering the prometheus endpoint. Looking at the code it has indeed reverted back to /metrics. Are there plans to change this? Right now I have to choose between showing metrics to the developers or capturing metrics with prometheus whereas I would very much like to do both.

**Comment by jtpio** [comment]
@colmaengus yes there will be a 0.4.0 release soon that should fix the clobbering: https://github.com/yuvipanda/nbresuse/pull/68
