### ISSUE TITLE
What to do if the memory is not visible on the screen?

### ISSUE THREAD

**Issue by jy2058** [yuvipanda/nbresuse#39]
![nbresuse_error](https://user-images.githubusercontent.com/44196188/82299257-40684f00-99f0-11ea-96ea-303dfc9dccb6.PNG)

i'm using docker jupyterhub/jupyterhub image
jupyterhub - 0.9.4
notebook - 6.0.3
psutil - 5.7.0
nbresuse - 0.3.4

Please tell me the solution.

**Comment by Gsbreddy** [comment]
Please use nbresuse==0.3.3

**Comment by jy2058** [comment]
@Gsbreddy thank you.
I tried nbresuse with version 0.3.3 
But it is still not visible on the screen.

![nb1](https://user-images.githubusercontent.com/44196188/82625270-ab4b9d00-9c1f-11ea-97a2-19008ec802fb.PNG)

Any help would be appreciated.

**Comment by jy2058** [comment]
Solved.
The memory is displayed on the screen after rebooting the docker container.
Thank you very much.

**Comment by Gsbreddy** [comment]
Great!
Please close this issue.
