### ISSUE TITLE
Memory not showing in notebooks

### ISSUE THREAD

**Issue by whositwhatnow** [yuvipanda/nbresuse#44]
Using systemdspawner in jupyterhub set limit to 1GB.
Install psutil, and nbresuse 0.3.4
memory limit not showing

**Comment by whositwhatnow** [comment]
Jun 11 08:32:08 jupyter bash: File "/usr/local/lib/python3.6/site-packages/nbresuse/prometheus.py", line 34, in __call__
Jun 11 08:32:08 jupyter bash: metrics = self.apply_memory_limits(memory_metrics())
Jun 11 08:32:08 jupyter bash: File "/usr/local/lib/python3.6/site-packages/nbresuse/prometheus.py", line 49, in apply_memory_limits
Jun 11 08:32:08 jupyter bash: metrics.max_memory = self.config.mem_limit
Jun 11 08:32:08 jupyter bash: AttributeError: can't set attribute

**Comment by Gsbreddy** [comment]
Please use nbresuse==0.3.3 and give it a try.

**Comment by whositwhatnow** [comment]
Working no problem with version 0.3.3
