### ISSUE TITLE
Bug with mem_warning_threshold == 0

### ISSUE THREAD

**Issue by mlucool** [yuvipanda/nbresuse#59]
When `mem_warning_threshold` is 0, it is [still used](https://github.com/yuvipanda/nbresuse/blob/d131aaa0b4d40dae0be897f7f35b4bcd83d4fe99/nbresuse/api.py#L39).

On the other hand the [documentation says](https://github.com/yuvipanda/nbresuse/blob/cdea3acb5e1e6bf8e3ec5d02091cb3964a0dac77/nbresuse/config.py#L67):
> Set to 0 to disable warning.

It looks like `cpu_warning_threshold` is handled correctly.

Please let me know if you'd like me to make a PR

**Comment by jtpio** [comment]
Thanks @mlucool for catching this.

Yes, a PR would be great!
