### ISSUE TITLE
Does this works with a Windows (10) O/S? 

### ISSUE THREAD

**Issue by jmbertoncelli** [yuvipanda/nbresuse#6]
[E 11:15:07.398 NotebookApp] Uncaught exception GET /metrics (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/metrics', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Language': 'en-US,en;q=0.8,fr;q=0.6', 'Accept-Encoding': 'gzip, deflate, sdch, br', 'X-Requested-With': 'XMLHttpRequest', 'Host': 'localhost:8888', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/notebooks/Dask/DUNS_EXPLODE.ipynb', 'Cookie': '_xsrf=2|1d88f79c|8ce8953f8aee94e480ea55651e84d5f0|1485879788; username-localhost-8888="2|1:0|10:1485969095|23:username-localhost-8888|44:NTM1Yjc3NWI0YjE2NGI5YTg0MmI1ODk4NzczMzAxZWY=|ef8abc29b00a0e429b29b5dad4c164ac63ba2ec84ef0041832f374144918bcdd"'})
    Traceback (most recent call last):
      File "C:\Users\jmbertoncelli\Miniconda2\envs\snake27.30\lib\site-packages\tornado\web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\Users\jmbertoncelli\Miniconda2\envs\snake27.30\lib\site-packages\nbresuse\handlers.py", line 21, in get
        self.finish(json.dumps(get_metrics()))
      File "C:\Users\jmbertoncelli\Miniconda2\envs\snake27.30\lib\site-packages\nbresuse\handlers.py", line 14, in get_metrics
        'memory': int(os.environ.get('MEM_LIMIT', None))
    TypeError: int() argument must be a string or a number, not 'NoneType'
[E 11:15:07.401 NotebookApp] {
      "Accept-Language": "en-US,en;q=0.8,fr;q=0.6",
      "Accept-Encoding": "gzip, deflate, sdch, br",
      "X-Requested-With": "XMLHttpRequest",
      "Host": "localhost:8888",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36",
      "Connection": "keep-alive",
      "Referer": "http://localhost:8888/notebooks/Dask/DUNS_EXPLODE.ipynb",
      "Cookie": "_xsrf=2|1d88f79c|8ce8953f8aee94e480ea55651e84d5f0|1485879788; username-localhost-8888=\"2|1:0|10:1485969095|23:username-localhost-8888|44:NTM1Yjc3NWI0YjE2NGI5YTg0MmI1ODk4NzczMzAxZWY=|ef8abc29b00a0e429b29b5dad4c164ac63ba2ec84ef0041832f374144918bcdd\""
    }

**Comment by cmoscardi** [comment]
I run into the same issue on Linux - it's because the `MEM_LIMIT` environment variable is not set.

**Comment by yuvipanda** [comment]
I fixed this by merging #5. Apologies for the very late fixups :)
