### ISSUE TITLE
nbresuse component for jupyterlab status bar

### ISSUE THREAD

**Issue by richagadgil** [yuvipanda/nbresuse#8]
The Jupyterlab status bar aims to show all relevant states of the notebook -- showing the current memory usage would be an asset. It would be great to integrate this into the status bar.

**Comment by yuvipanda** [comment]
+1, that sounds great! I won't have the cycles to do this, however. Feel free to start a PR! I can also give you merge rights here.

**Comment by mathematicalmichael** [comment]
@richagadgil would love this feature. wish I knew how to add it.

**Comment by jtpio** [comment]
Looks like it's coming soon :tada:

https://github.com/jupyterlab/jupyterlab/blob/f948692b5dd828801a2c389c632332f1b5ed43f3/packages/statusbar-extension/src/index.ts#L220-L245

xref https://github.com/jupyterlab/jupyterlab/issues/5352

**Comment by mathematicalmichael** [comment]
@jtpio whoa! awesome. thanks! would you mind pinging this thread when it does (or when I'm able to pull a branch to test it out?)

**Comment by jtpio** [comment]
@mathematicalmichael you can setup a dev environment by following these instructions, and try it on master: https://github.com/jupyterlab/jupyterlab/blob/master/CONTRIBUTING.md#setting-up-a-development-environment

And install nbresuse in the same environment: `pip install nbresuse`

![image](https://user-images.githubusercontent.com/591645/51763756-91ee1b80-20d3-11e9-84a1-b6d29061e709.png)

**Comment by mathematicalmichael** [comment]
@jtpio oh that was rather painless. Thanks for pointing me to the right spot in the docs! Had never opened the contributing one because I'm not a JS dev. Silly me...

Very neat, though not what I quite expected. Do you happen to know if it remain on bottom there? Seems to be an inefficient use of space given that it could all fit in the same row as File/Edit/etc

**Comment by jtpio** [comment]
@mathematicalmichael glad you got it setup!

I don't know of any plans to move it somewhere else, but the best might be to open an issue to raise this question (https://github.com/jupyterlab/jupyterlab/issues), or ask on gitter (https://gitter.im/jupyterlab/jupyterlab).

An alternative would be to implement a third-party JupyterLab extension and experiment with different positioning.

**Comment by jtpio** [comment]
> Seems to be an inefficient use of space given that it could all fit in the same row as File/Edit/etc

@mathematicalmichael this made me want to experiment a little bit over the past few days with a "top bar" extension for JupyterLab.

Here is the repo: https://github.com/jtpio/jupyterlab-topbar. You can actually install it, or try it out with Binder.

The idea is to indeed expose the space next to the menu so the other extensions can use it.
One example is the [system monitor extension](https://github.com/jtpio/jupyterlab-topbar/tree/master/packages/jupyterlab-system-monitor) which is an alternative frontend for displaying the memory usage for the notebook server, still based on the data exposed by `nbresuse`.

**Comment by mathematicalmichael** [comment]
@jtpio you're amazing. I love your TODO list as well. As I didn't really need the other features in the bottom-bar, this is a great solution for the time being!

**Comment by thoralf-gutierrez** [comment]
Just tried installing nbresuse and the memory usage just showed up in the bottom status bar, so I think we can close this issue :+1:

**Comment by krinsman** [comment]
@thoralf-gutierrez Yes I believe you're right, @richagadgil implemented this and it was merged into JupyterLab master. It works for me as well. I will close this issue now at least provisionally.

**Comment by jtpio** [comment]
Yes it's tracked in #36.
